{% set name = "TileDB" %}
{% set version = "1.4.1" %}
{% set sha256 = "a278ebef1acc6e329eb9816502dda6b3c8b35c4853745a222111626c251b2845" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/TileDB-Inc/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [win32]
  skip: True  # [win and vc<14]
  features:  # [win]
    - vc14  # [win]

requirements:
  build:
    - cmake
    - pkg-config  # [not win]
    - {{ compiler('cxx') }}
  host:
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - tbb-devel 2019.1
  run:
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - tbb 2019.1

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
   
    - test -e $PREFIX/include/tiledb/tiledb.h  # [unix]
    - test -e $PREFIX/include/tiledb/tiledb  # [unix]
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT  # [linux]
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT  # [osx]

    - if exist %LIBRARY_INC%\\tiledb\\tiledb (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_INC%\\tiledb\\tiledb.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\tiledb.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\cmake\\TileDB\\TileDBConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\tiledb.dll (exit 0) else (exit 1)  # [win]

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'TileDB sparse and dense multi-dimensional array data management'
  description: |
    TileDB is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can effectively store dense and sparse array data with
    support for fast updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: http://docs.tiledb.io
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  recipe-maintainers:
    - stavrospapadopoulos
    - jakebolewski
    - tdenniston
